name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "10.0"
    - name: Build FaruOS
      run: |
        git submodule init
        git submodule update
        make -C limine -j$(nproc)
        make -C src/libc -j$(nproc)
        make -C src/kernel -j$(nproc)
        make -j$(nproc)
